### PR TITLE
Add sorting guild members by note

### PR DESCRIPTION
**Pull request by Disparity**
It extends the ability to sort the list of guild members through your notes. In particular, in the notes can be saved iLvl and sort the list by him, at the invitation of the raid.

### CODE REVIEW

**Comment by solocommand** [comment]
@Disparity Thanks for the contribution! @kballard This looks fine to me, any concerns?

**Comment by kballard** [comment]
This should work for sorting notes, but it won't actually do what the described use-case wants. Specifically, this is doing a normal lexicographical sort, but the described use-case wants a numerical sort.

**Comment by Disparity** [comment]
Yes, I understand that this is not an integer comparison, but just text. For myself, the problem was solved by adding different numbers of spaces instead of leading zeros. Whitespace "less" any character numbers, so everything works as expected.
ilvl is a private example that I have needed, but the note can be any text, because the field is a text note =)

**Comment by kballard** [comment]
Well, as long as you're aware of the limitation, then it looks fine to me. Thanks for the PR!

**Pull request merged**
